package database

var colecoesMongoJogo = []string{
	"accounts",
	"auctions",
	"augmentations",
	"bbsFavorite",
	"bbsForum",
	"bbsMail",
	"bbsPost",
	"bbsTopic",
	"bookmarks",
	"bufferSchemes",
	"buylists",
	"castle",
	"castleDoorupgrade",
	"castleManorProcure",
	"castleManorProduction",
	"castleTrapupgrade",
	"characterHennas",
	"characterMacroses",
	"characterMemo",
	"characterQuests",
	"characterRaidPoints",
	"characterRecipebook",
	"characterRecommends",
	"characterRelations",
	"characterShortcuts",
	"characterSkills",
	"characterSkillsSave",
	"characterSubclasses",
	"characters",
	"clanData",
	"clanPrivs",
	"clanSkills",
	"clanSubpledges",
	"clanWars",
	"clanhall",
	"clanhallFlagwarAttackers",
	"clanhallFlagwarMembers",
	"clanhallFlagwarOwnerNpcs",
	"clanhallFunctions",
	"clanhallSiegeAttackers",
	"cursedWeapons",
	"fishingChampionship",
	"games",
	"gameservers",
	"grandbossList",
	"heroes",
	"heroesDiary",
	"items",
	"itemsOnGround",
	"mdtBets",
	"mdtHistory",
	"modsWedding",
	"olympiadFights",
	"olympiadNobles",
	"olympiadNoblesEom",
	"petition",
	"petitionMessage",
	"pets",
	"rainbowspringsAttackerList",
	"serverMemo",
	"sevenSigns",
	"sevenSignsFestival",
	"sevenSignsStatus",
	"siegeClans",
	"spawnData",
}

func ListarColecoesMongoJogo() []string {
	resultado := make([]string, len(colecoesMongoJogo))
	copy(resultado, colecoesMongoJogo)
	return resultado
}
